### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by hohaidang** [dr-kino/BraveCoverage#1]
I'm using Ubuntu 18.04
Installed gtest, cmake
I have this error when trying to run this command
$ cmake .. 
Maybe it cannot find out Boost Directory, 
![image](https://user-images.githubusercontent.com/22592185/92446724-35306d80-f1f1-11ea-82fd-a5e58b36fb5f.png)

**Comment by dr-kino** [comment]
Hi @hohaidang, sorry for being late. I hope you managed to solve the issue, for sure you have a issue with the boost library.

If you still having the same issue and you do not need to use the boost library in your project, I would suggest to modify slightly this project and remove the user interface code. Boost is needed only for this step.

Thanks in advance.
