### ISSUE TITLE
googletest Build Issue

### ISSUE THREAD

**Issue by davidefolli93** [dr-kino/BraveCoverage#2]
Hi,

trying to compile googletest framework according to the README istructions, an error is thrown when executing **sudo cmake CMakeLists.txt**:
`-- Detecting C compile features - done
CMake Warning at /home/davide/sources/CoverageAnalysis/GoogleTest/googletest/CMakeLists.txt:54 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.
`

I managed to solve the issue executing the command from the parent directory.
It seems that 
`cd GoogleTest/googlemock`
maybe not necessary

**Comment by dr-kino** [comment]
Hi @davidefolli93, thanks for your report. Now it is fixed!
